Repository team-moabam/moabam-BE, pull requests merged in 2023-12, with the labels that each got.

#221 fix: 인증된 참여자의 방 나가기 후 방 정보 불러오기 안되는 버그 해결
  src/main/java/com/moabam/api/application/room/CertificationService.java
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/application/room/SearchService.java
  src/main/java/com/moabam/api/domain/room/repository/CertificationsSearchRepository.java
  src/main/java/com/moabam/api/domain/room/repository/ParticipantSearchRepository.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
Labels: 🍀 BE, 🐛 fix

#223 fix: 방의 인증 시간에는 입장하지 못하도록 수정
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
Labels: 🍀 BE, 🐛 fix

#226 fix: Room soft delete로 변경
  infra/mysql/initdb.d/init.sql
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/domain/room/Participant.java
  src/main/java/com/moabam/api/domain/room/Room.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
Labels: 🍀 BE, 🐛 fix

#228 fix: 참여자 목록이 복사되는 버그 해결
  src/main/java/com/moabam/api/application/room/CertificationService.java
  src/main/java/com/moabam/api/application/room/SearchService.java
Labels: 🍀 BE, 🐛 fix

#230 fix: 기여도 버그 해결
  src/main/java/com/moabam/api/application/room/SearchService.java
Labels: 🍀 BE, 🐛 fix

#233 fix: 인증율 하락 버그 수정
  src/main/java/com/moabam/api/application/room/SearchService.java
  src/main/java/com/moabam/api/domain/room/repository/CertificationsSearchRepository.java
  src/main/java/com/moabam/api/domain/room/repository/ParticipantSearchRepository.java
  src/test/java/com/moabam/api/application/room/RoomServiceConcurrencyTest.java
  src/test/java/com/moabam/api/application/room/SearchServiceTest.java
Labels: 🍀 BE, 🐛 fix

#234 fix: admin token fix
  src/main/java/com/moabam/api/application/auth/AuthorizationService.java
  src/main/java/com/moabam/global/common/util/CookieUtils.java
Labels: 🍀 BE, 🐛 fix

#237 feat: 에러 로그 슬랙 연동 구현
  build.gradle
  src/main/java/com/moabam/api/infrastructure/payment/TossPaymentService.java
  src/main/resources/logback-spring.xml
Labels: ✨ feature, 🍀 BE

#235 fix: admin token fix
  src/main/java/com/moabam/api/application/auth/AuthorizationService.java
  src/main/java/com/moabam/global/auth/filter/AuthorizationFilter.java
  src/main/java/com/moabam/global/common/util/CookieUtils.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/global/common/util/CookieMakeTest.java
Labels: 🍀 BE, 🐛 fix

#239 fix: date equals 적용
  src/main/java/com/moabam/api/application/room/SearchService.java
Labels: 🍀 BE, 🐛 fix

#245 chore: main 반영사항 merge
  .github/workflows/develop-cd.yml
  .github/workflows/prod-cd.yml
Labels: 🍀 BE, 🐛 fix

#254 refactor: 검색 기능 쿼리 변경
  infra/mysql/initdb.d/init.sql
  src/main/java/com/moabam/api/application/room/SearchService.java
  src/main/java/com/moabam/api/domain/room/Room.java
  src/main/java/com/moabam/api/domain/room/Routine.java
  src/main/java/com/moabam/api/domain/room/repository/RoomSearchRepository.java
  src/main/java/com/moabam/global/common/util/SystemClockHolder.java
  src/main/java/com/moabam/global/config/SqlFunctionContributor.java
  src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  src/test/java/com/moabam/api/application/room/SearchServiceTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
  src/test/resources/application.yml
Labels: ♻️ refactor, 🍀 BE
