Repository team-moabam/moabam-BE, pull requests merged in 2023-10, with the labels that each got.

#2 chore: sonarcloud, checkstyle, jacoco 적용
  .editorconfig
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  config/naver-checkstyle-rules.xml
  config/naver-intellij-formatter-custom.xml
Labels: ⚙️ setting, 🍀 BE

#4 feat: 공통된 클래스 추가 작업
  src/main/java/com/moabam/global/common/entity/BaseTimeEntity.java
  src/main/java/com/moabam/global/common/util/DynamicQuery.java
  src/main/java/com/moabam/global/config/JpaConfig.java
  src/main/java/com/moabam/global/config/WebConfig.java
  src/main/java/com/moabam/global/error/exception/BadRequestException.java
  src/main/java/com/moabam/global/error/exception/ConflictException.java
  src/main/java/com/moabam/global/error/exception/ForbiddenException.java
  src/main/java/com/moabam/global/error/exception/MoabamException.java
  src/main/java/com/moabam/global/error/exception/NotFoundException.java
  src/main/java/com/moabam/global/error/exception/UnauthorizedException.java
  src/main/java/com/moabam/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/main/java/com/moabam/global/error/model/ErrorResponse.java
Labels: ✨ feature, 🍀 BE

#10 fix: intellij-formatter line-separator
  .editorconfig
  config/naver-checkstyle-rules.xml
  config/naver-intellij-formatter-custom.xml
Labels: 🍀 BE, 🐛 fix
