Repository team-moabam/moabam-BE, pull requests merged in 2023-11, with the labels that each got.

#24 feat: Authorization Server로 부터 토큰 발급 기능 추가
  src/main/java/com/moabam/api/application/AuthenticationService.java
  src/main/java/com/moabam/api/application/OAuth2AuthorizationServerRequestService.java
  src/main/java/com/moabam/api/domain/entity/Member.java
  src/main/java/com/moabam/api/dto/AuthorizationCodeResponse.java
  src/main/java/com/moabam/api/dto/AuthorizationTokenRequest.java
  src/main/java/com/moabam/api/dto/AuthorizationTokenResponse.java
  src/main/java/com/moabam/api/dto/OAuthMapper.java
  src/main/java/com/moabam/api/presentation/MemberController.java
  src/main/java/com/moabam/global/common/util/OAuthParameterNames.java
  src/main/java/com/moabam/global/config/OAuthConfig.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/api/application/AuthenticationServiceTest.java
  src/test/java/com/moabam/api/application/OAuth2AuthorizationServerRequestServiceTest.java
  src/test/java/com/moabam/api/domain/entity/MemberTest.java
  src/test/java/com/moabam/api/presentation/MemberControllerTest.java
  src/test/java/com/moabam/fixture/AuthorizationTokenResponseFixture.java
  src/test/resources/application-test.yml
Labels: ✨ feature, 🍀 BE

#28 feat: 방 참여, 나가기 기능 구현
  build.gradle
  src/main/java/com/moabam/api/application/RoomService.java
  src/main/java/com/moabam/api/domain/entity/Member.java
  src/main/java/com/moabam/api/domain/entity/Participant.java
  src/main/java/com/moabam/api/domain/entity/Room.java
  src/main/java/com/moabam/api/domain/repository/ParticipantSearchRepository.java
  src/main/java/com/moabam/api/dto/EnterRoomRequest.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/api/presentation/BugControllerTest.java
  src/test/java/com/moabam/api/presentation/MemberControllerTest.java
  src/test/java/com/moabam/api/presentation/ProductControllerTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
  src/test/resources/application.yml
Labels: 🍀 BE

#36 feat: 방 수정에 필요한 필드 추가
  src/main/java/com/moabam/api/dto/ModifyRoomRequest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
Labels: ✨ feature, 🍀 BE

#43 feat: 콕 찌르기 API 구현 (feat. RestDoc, Embedded Redis)
  .github/workflows/ci.yml
  .github/workflows/develop-cd.yml
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/notification.adoc
  src/main/java/com/moabam/api/application/AuthenticationService.java
  src/main/java/com/moabam/api/application/NotificationService.java
  src/main/java/com/moabam/api/application/OAuth2AuthorizationServerRequestService.java
  src/main/java/com/moabam/api/domain/repository/NotificationRepository.java
  src/main/java/com/moabam/api/presentation/NotificationController.java
  src/main/java/com/moabam/global/common/constant/FcmConstant.java
  src/main/java/com/moabam/global/common/constant/GlobalConstant.java
  src/main/java/com/moabam/global/common/constant/RedisConstant.java
  src/main/java/com/moabam/global/common/repository/StringRedisRepository.java
  src/main/java/com/moabam/global/config/EmbeddedRedisConfig.java
  src/main/java/com/moabam/global/config/FcmConfig.java
  src/main/java/com/moabam/global/error/exception/MoabamException.java
  src/main/java/com/moabam/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/main/resources/binary/redis/redis-server-arm64
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/NotificationServiceTest.java
  src/test/java/com/moabam/api/application/OAuth2AuthorizationServerRequestServiceTest.java
  src/test/java/com/moabam/api/domain/repository/NotificationRepositoryTest.java
  src/test/java/com/moabam/api/presentation/MemberControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
  src/test/java/com/moabam/fixture/MemberFixture.java
  src/test/java/com/moabam/fixture/RoomFixture.java
  src/test/java/com/moabam/global/common/repository/StringRedisRepositoryTest.java
  src/test/resources/application.yml
Labels: ✨ feature, 🍀 BE

#45 feat: 아이템 적용 기능 구현
  src/main/java/com/moabam/api/application/ItemService.java
  src/main/java/com/moabam/api/domain/entity/Inventory.java
  src/main/java/com/moabam/api/domain/repository/InventorySearchRepository.java
  src/main/java/com/moabam/api/presentation/ItemController.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/api/application/AuthenticationServiceTest.java
  src/test/java/com/moabam/api/application/BugServiceTest.java
  src/test/java/com/moabam/api/application/ItemServiceTest.java
  src/test/java/com/moabam/api/application/ProductServiceTest.java
  src/test/java/com/moabam/api/domain/entity/MemberTest.java
  src/test/java/com/moabam/api/domain/repository/InventorySearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/repository/ItemSearchRepositoryTest.java
  src/test/java/com/moabam/api/presentation/BugControllerTest.java
  src/test/java/com/moabam/api/presentation/ItemControllerTest.java
  src/test/java/com/moabam/api/presentation/MemberControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
  src/test/java/com/moabam/api/presentation/ProductControllerTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
  src/test/java/com/moabam/support/annotation/QuerydslRepositoryTest.java
  src/test/java/com/moabam/support/config/TestQuerydslConfig.java
  src/test/java/com/moabam/support/fixture/AuthorizationResponseFixture.java
  src/test/java/com/moabam/support/fixture/BugFixture.java
  src/test/java/com/moabam/support/fixture/InventoryFixture.java
  src/test/java/com/moabam/support/fixture/ItemFixture.java
  src/test/java/com/moabam/support/fixture/MemberFixture.java
  src/test/java/com/moabam/support/fixture/ProductFixture.java
Labels: ✨ feature, 🍀 BE

#49 refactor: 방 관련 기능 리팩터링
  src/main/java/com/moabam/api/application/RoomService.java
  src/main/java/com/moabam/api/domain/entity/Room.java
  src/main/java/com/moabam/api/domain/entity/Routine.java
  src/main/java/com/moabam/api/domain/repository/CertificationsSearchRepository.java
  src/main/java/com/moabam/api/dto/CertificationsMapper.java
  src/main/java/com/moabam/api/dto/CreateRoomRequest.java
  src/main/java/com/moabam/api/dto/ModifyRoomRequest.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/api/application/RoomServiceTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
Labels: ♻️ refactor, 🍀 BE

#53 feat: 콕 찌르기 여부를 확인하는 기능 구현 및 테스트
  src/main/java/com/moabam/api/application/NotificationService.java
  src/main/java/com/moabam/api/domain/repository/ParticipantSearchRepository.java
  src/main/java/com/moabam/api/dto/KnockNotificationStatusResponse.java
  src/main/java/com/moabam/api/dto/NotificationMapper.java
  src/test/java/com/moabam/api/application/NotificationServiceTest.java
  src/test/java/com/moabam/api/domain/repository/ParticipantSearchRepositoryTest.java
  src/test/java/com/moabam/support/fixture/ParticipantFixture.java
Labels: ✨ feature, 🍀 BE

#57 feat: 쿠폰 발행 기능 구현 및 테스트
  src/docs/asciidoc/coupon.adoc
  src/main/java/com/moabam/api/application/CouponService.java
  src/main/java/com/moabam/api/domain/entity/Coupon.java
  src/main/java/com/moabam/api/domain/entity/enums/CouponType.java
  src/main/java/com/moabam/api/domain/repository/CouponRepository.java
  src/main/java/com/moabam/api/dto/CouponMapper.java
  src/main/java/com/moabam/api/dto/CreateCouponRequest.java
  src/main/java/com/moabam/api/presentation/CouponController.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/main/resources/static/docs/coupon.html
  src/test/java/com/moabam/api/application/CouponServiceTest.java
  src/test/java/com/moabam/api/domain/entity/CouponTest.java
  src/test/java/com/moabam/api/domain/entity/enums/CouponTypeTest.java
  src/test/java/com/moabam/api/dto/CreateCouponRequestTest.java
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/support/fixture/CouponFixture.java
  src/test/java/com/moabam/support/fixture/CouponSnippetFixture.java
Labels: ✨ feature, 🍀 BE

#58 feat: 쿠폰 삭제 기능 구현
  src/docs/asciidoc/coupon.adoc
  src/docs/asciidoc/notification.adoc
  src/main/java/com/moabam/api/application/CouponService.java
  src/main/java/com/moabam/api/presentation/CouponController.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/CouponServiceTest.java
  src/test/java/com/moabam/api/application/NotificationServiceTest.java
  src/test/java/com/moabam/api/domain/repository/NotificationRepositoryTest.java
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
  src/test/java/com/moabam/global/common/repository/StringRedisRepositoryTest.java
Labels: ✨ feature, 🍀 BE

#60 feat: 특정 쿠폰 및 상태에 따른 쿠폰 조회 기능 구현 및 테스트
  src/docs/asciidoc/coupon.adoc
  src/main/java/com/moabam/api/application/CouponService.java
  src/main/java/com/moabam/api/domain/entity/Coupon.java
  src/main/java/com/moabam/api/domain/repository/CouponSearchRepository.java
  src/main/java/com/moabam/api/dto/CouponMapper.java
  src/main/java/com/moabam/api/dto/CouponResponse.java
  src/main/java/com/moabam/api/dto/CouponSearchRequest.java
  src/main/java/com/moabam/api/dto/CreateCouponRequest.java
  src/main/java/com/moabam/api/presentation/CouponController.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/CouponServiceTest.java
  src/test/java/com/moabam/api/domain/entity/CouponTest.java
  src/test/java/com/moabam/api/domain/repository/CouponSearchRepositoryTest.java
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
  src/test/java/com/moabam/support/fixture/CouponFixture.java
  src/test/java/com/moabam/support/fixture/CouponSnippetFixture.java
  src/test/java/com/moabam/support/fixture/ErrorSnippetFixture.java
Labels: ✨ feature, 🍀 BE

#62 feat: 회원 annotation 기능 추가 및 테스트 인터페이스 제공
  src/main/java/com/moabam/api/application/AuthorizationService.java
  src/main/java/com/moabam/api/application/JwtAuthenticationService.java
  src/main/java/com/moabam/api/application/JwtProviderService.java
  src/main/java/com/moabam/api/application/MemberService.java
  src/main/java/com/moabam/api/domain/entity/Member.java
  src/main/java/com/moabam/api/dto/AuthorizationMapper.java
  src/main/java/com/moabam/api/dto/AuthorizationMember.java
  src/main/java/com/moabam/api/dto/LoginResponse.java
  src/main/java/com/moabam/api/dto/MemberMapper.java
  src/main/java/com/moabam/api/dto/PathMapper.java
  src/main/java/com/moabam/api/dto/PublicClaim.java
  src/main/java/com/moabam/api/presentation/MemberController.java
  src/main/java/com/moabam/global/common/annotation/CurrentMember.java
  src/main/java/com/moabam/global/common/handler/CurrentMemberArgumentResolver.java
  src/main/java/com/moabam/global/common/handler/PathResolver.java
  src/main/java/com/moabam/global/common/util/AuthorizationThreadLocal.java
  src/main/java/com/moabam/global/common/util/CookieUtils.java
  src/main/java/com/moabam/global/config/WebConfig.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/main/java/com/moabam/global/filter/AuthorizationFilter.java
  src/main/java/com/moabam/global/filter/PathFilter.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/AuthorizationServiceTest.java
  src/test/java/com/moabam/api/application/JwtAuthenticationServiceTest.java
  src/test/java/com/moabam/api/application/JwtProviderServiceTest.java
  src/test/java/com/moabam/api/application/MemberServiceTest.java
  src/test/java/com/moabam/api/domain/repository/MemberRepositoryTest.java
  src/test/java/com/moabam/api/presentation/BugControllerTest.java
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/api/presentation/ItemControllerTest.java
  src/test/java/com/moabam/api/presentation/MemberControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
  src/test/java/com/moabam/api/presentation/ProductControllerTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
  src/test/java/com/moabam/global/common/handler/CurrentMemberArgumentResolverTest.java
  src/test/java/com/moabam/global/common/handler/PathResolverTest.java
  src/test/java/com/moabam/global/filter/AuthorizationFilterTest.java
  src/test/java/com/moabam/global/filter/PathFilterTest.java
  src/test/java/com/moabam/support/annotation/WithMember.java
  src/test/java/com/moabam/support/common/FilterProcessExtension.java
  src/test/java/com/moabam/support/common/RestDocsFactory.java
  src/test/java/com/moabam/support/common/WithFilterSupporter.java
  src/test/java/com/moabam/support/common/WithoutFilterSupporter.java
  src/test/java/com/moabam/support/fixture/JwtProviderFixture.java
  src/test/java/com/moabam/support/fixture/PublicClaimFixture.java
  src/test/resources/application.yml
Labels: ✨ feature, 🍀 BE

#72 fix: config 최신화
  src/main/java/com/moabam/global/config/WebConfig.java
Labels: 🍀 BE

#79 refactor: 방 관련 서비스 분리
  .gitignore
  src/main/java/com/moabam/api/application/room/RoomCertificationService.java
  src/main/java/com/moabam/api/application/room/RoomSearchService.java
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/RoomCertificationServiceTest.java
  src/test/java/com/moabam/api/application/RoomServiceTest.java
Labels: ♻️ refactor, 🍀 BE

#81 feat: 방장 위임 기능 구현
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/test/java/com/moabam/api/application/RoomServiceTest.java
Labels: ✨ feature, 🍀 BE

#80 feat: 오늘 보상 벌레 조회 기능 구현
  src/main/java/com/moabam/api/application/bug/BugMapper.java
  src/main/java/com/moabam/api/application/bug/BugService.java
  src/main/java/com/moabam/api/domain/repository/BugHistorySearchRepository.java
  src/main/java/com/moabam/api/dto/TodayBugResponse.java
  src/main/java/com/moabam/api/presentation/BugController.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/presentation/BugControllerTest.java
  src/test/java/com/moabam/support/fixture/BugHistoryFixture.java
Labels: ✨ feature, 🍀 BE

#82 refactor: 쿠폰 및 알림 Authorization Member 적용 리팩터링
  src/main/java/com/moabam/api/application/coupon/CouponService.java
  src/main/java/com/moabam/api/application/notification/NotificationService.java
  src/main/java/com/moabam/api/presentation/CouponController.java
  src/main/java/com/moabam/api/presentation/NotificationController.java
  src/main/java/com/moabam/global/auth/annotation/MemberTest.java
  src/test/java/com/moabam/api/application/CouponServiceTest.java
  src/test/java/com/moabam/api/application/NotificationServiceTest.java
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
Labels: ♻️ refactor, 🍀 BE

#87 refactor: 아이템/상품 컨트롤러 테스트 리팩토링 및 @CurrentMember 적용
  src/main/java/com/moabam/api/presentation/ItemController.java
  src/test/java/com/moabam/api/presentation/ItemControllerTest.java
  src/test/java/com/moabam/api/presentation/ProductControllerTest.java
Labels: ♻️ refactor, 🍀 BE

#89 refactor: 방 컨트롤러 @CurrentMember 적용, 통합 테스트 리팩토링
  src/main/java/com/moabam/api/application/bug/BugService.java
  src/main/java/com/moabam/api/application/room/RoomSearchService.java
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/domain/bug/repository/BugHistorySearchRepository.java
  src/main/java/com/moabam/api/domain/room/repository/RoutineSearchRepository.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/room/RoomCertificationServiceTest.java
  src/test/java/com/moabam/api/application/room/RoomServiceTest.java
  src/test/java/com/moabam/api/domain/room/CertificationTest.java
  src/test/java/com/moabam/api/domain/room/RoomTest.java
  src/test/java/com/moabam/api/domain/room/repository/CertificationsSearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/room/repository/ParticipantSearchRepositoryTest.java
  src/test/java/com/moabam/api/presentation/BugControllerTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
  src/test/java/com/moabam/support/fixture/RoomFixture.java
Labels: ♻️ refactor, 🍀 BE

#95 feat: 참여중인 방 목록 조회
  src/main/java/com/moabam/api/application/room/RoomCertificationService.java
  src/main/java/com/moabam/api/application/room/RoomSearchService.java
  src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
  src/main/java/com/moabam/api/domain/room/repository/DailyMemberCertificationRepository.java
  src/main/java/com/moabam/api/domain/room/repository/DailyRoomCertificationRepository.java
  src/main/java/com/moabam/api/domain/room/repository/ParticipantSearchRepository.java
  src/main/java/com/moabam/api/dto/room/MyRoomResponse.java
  src/main/java/com/moabam/api/dto/room/MyRoomsResponse.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/test/java/com/moabam/api/application/room/RoomSearchServiceTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
  src/test/java/com/moabam/support/fixture/RoomFixture.java
Labels: ✨ feature, 🍀 BE

#97 refactor: 벌레 컨트롤러 및 테스트 패키지 구조 변경
  src/main/java/com/moabam/api/application/bug/BugService.java
  src/main/java/com/moabam/api/application/product/ProductService.java
  src/main/java/com/moabam/api/domain/product/repository/ProductRepository.java
  src/main/java/com/moabam/api/presentation/BugController.java
  src/main/java/com/moabam/api/presentation/ProductController.java
  src/test/java/com/moabam/api/application/ProductServiceTest.java
  src/test/java/com/moabam/api/application/bug/BugServiceTest.java
  src/test/java/com/moabam/api/application/item/ItemServiceTest.java
  src/test/java/com/moabam/api/domain/bug/BugTest.java
  src/test/java/com/moabam/api/domain/item/ItemTest.java
  src/test/java/com/moabam/api/domain/item/repository/InventorySearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/item/repository/ItemSearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/product/ProductTest.java
  src/test/java/com/moabam/api/presentation/BugControllerTest.java
  src/test/java/com/moabam/api/presentation/ProductControllerTest.java
Labels: ♻️ refactor, 🍀 BE

#100 feat: 아이템 목록 조회 Response에 현재 적용된 아이템 속성 추가
  src/main/java/com/moabam/api/application/bug/BugMapper.java
  src/main/java/com/moabam/api/application/bug/BugService.java
  src/main/java/com/moabam/api/application/item/ItemMapper.java
  src/main/java/com/moabam/api/application/item/ItemService.java
  src/main/java/com/moabam/api/dto/bug/TodayBugResponse.java
  src/main/java/com/moabam/api/dto/item/ItemsResponse.java
  src/main/java/com/moabam/api/presentation/BugController.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/api/application/item/ItemServiceTest.java
  src/test/java/com/moabam/api/presentation/BugControllerTest.java
  src/test/java/com/moabam/api/presentation/ItemControllerTest.java
Labels: ✨ feature, 🍀 BE

#101 feat: 방 참여 기록 조회 기능 구현
  src/main/java/com/moabam/api/application/room/RoomSearchService.java
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
  src/main/java/com/moabam/api/domain/room/repository/ParticipantSearchRepository.java
  src/main/java/com/moabam/api/dto/room/RoomHistoryResponse.java
  src/main/java/com/moabam/api/dto/room/RoomsHistoryResponse.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/test/java/com/moabam/api/application/room/RoomSearchServiceTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
Labels: ✨ feature, 🍀 BE

#105 refactor: 쿠폰, 알림 및 토큰 패키지 및 클래스명 변경
  src/main/java/com/moabam/api/application/auth/AuthorizationService.java
  src/main/java/com/moabam/api/application/notification/NotificationMapper.java
  src/main/java/com/moabam/api/application/notification/NotificationService.java
  src/main/java/com/moabam/api/domain/auth/repository/TokenRepository.java
  src/main/java/com/moabam/api/domain/notification/repository/NotificationRepository.java
  src/main/java/com/moabam/api/infrastructure/fcm/FcmService.java
  src/main/java/com/moabam/api/infrastructure/redis/HashRedisRepository.java
  src/main/java/com/moabam/api/infrastructure/redis/StringRedisRepository.java
  src/main/java/com/moabam/global/common/util/GlobalConstant.java
  src/main/java/com/moabam/global/config/FcmConfig.java
  src/main/java/com/moabam/global/config/RedisConfig.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/AuthorizationServiceTest.java
  src/test/java/com/moabam/api/application/notification/NotificationServiceTest.java
  src/test/java/com/moabam/api/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/moabam/api/domain/repository/TokenRepostiroyTest.java
  src/test/java/com/moabam/api/infrastructure/fcm/FcmServiceTest.java
  src/test/java/com/moabam/api/infrastructure/redis/HashRedisRepositoryTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
Labels: ♻️ refactor, 🍀 BE

#109 feat: 방 전체 목록 조회 기능 구현
  src/main/java/com/moabam/api/application/member/MemberService.java
  src/main/java/com/moabam/api/application/room/RoomSearchService.java
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
  src/main/java/com/moabam/api/domain/member/repository/MemberSearchRepository.java
  src/main/java/com/moabam/api/domain/room/Room.java
  src/main/java/com/moabam/api/domain/room/repository/RoomSearchRepository.java
  src/main/java/com/moabam/api/domain/room/repository/RoutineSearchRepository.java
  src/main/java/com/moabam/api/dto/room/SearchAllRoomResponse.java
  src/main/java/com/moabam/api/dto/room/SearchAllRoomsResponse.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/main/java/com/moabam/global/common/util/GlobalConstant.java
  src/test/java/com/moabam/api/application/room/RoomSearchServiceTest.java
  src/test/java/com/moabam/api/application/room/RoomServiceTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
  src/test/java/com/moabam/support/fixture/RoomFixture.java
Labels: ✨ feature, 🍀 BE

#113 feat: 결제 요청 기능 구현
  src/main/java/com/moabam/api/application/payment/PaymentService.java
  src/main/java/com/moabam/api/domain/payment/Order.java
  src/main/java/com/moabam/api/domain/payment/Payment.java
  src/main/java/com/moabam/api/domain/payment/PaymentStatus.java
  src/main/java/com/moabam/api/dto/payment/PaymentRequest.java
  src/main/java/com/moabam/api/presentation/BugController.java
  src/main/java/com/moabam/api/presentation/PaymentController.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/api/application/payment/PaymentServiceTest.java
  src/test/java/com/moabam/api/domain/payment/OrderTest.java
  src/test/java/com/moabam/api/domain/payment/PaymentTest.java
  src/test/java/com/moabam/api/presentation/PaymentControllerTest.java
  src/test/java/com/moabam/support/fixture/PaymentFixture.java
Labels: ✨ feature, 🍀 BE

#114 feat: 쿠폰 발급 요청 기능 구현
  src/docs/asciidoc/coupon.adoc
  src/main/java/com/moabam/api/application/coupon/CouponMapper.java
  src/main/java/com/moabam/api/application/coupon/CouponQueueService.java
  src/main/java/com/moabam/api/application/coupon/CouponService.java
  src/main/java/com/moabam/api/application/notification/NotificationService.java
  src/main/java/com/moabam/api/domain/coupon/Coupon.java
  src/main/java/com/moabam/api/domain/coupon/repository/CouponQueueRepository.java
  src/main/java/com/moabam/api/domain/coupon/repository/CouponRepository.java
  src/main/java/com/moabam/api/domain/coupon/repository/CouponSearchRepository.java
  src/main/java/com/moabam/api/infrastructure/redis/StringRedisRepository.java
  src/main/java/com/moabam/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/moabam/api/presentation/CouponController.java
  src/main/java/com/moabam/api/presentation/NotificationController.java
  src/main/java/com/moabam/global/common/util/GlobalConstant.java
  src/main/java/com/moabam/global/config/EmbeddedRedisConfig.java
  src/main/java/com/moabam/global/config/RedisConfig.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/coupon/CouponQueueServiceTest.java
  src/test/java/com/moabam/api/application/coupon/CouponServiceTest.java
  src/test/java/com/moabam/api/application/notification/NotificationServiceTest.java
  src/test/java/com/moabam/api/domain/coupon/CouponTest.java
  src/test/java/com/moabam/api/domain/coupon/repository/CouponQueueRepositoryTest.java
  src/test/java/com/moabam/api/domain/coupon/repository/CouponSearchRepositoryTest.java
  src/test/java/com/moabam/api/infrastructure/redis/StringRedisRepositoryTest.java
  src/test/java/com/moabam/api/infrastructure/redis/ZSetRedisRepositoryTest.java
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/support/fixture/CouponFixture.java
  src/test/resources/application.yml
Labels: ✨ feature, 🍀 BE

#117 feat: 방 상세 정보 조회 기능 추가 변경
  src/main/java/com/moabam/api/application/notification/NotificationMapper.java
  src/main/java/com/moabam/api/application/notification/NotificationService.java
  src/main/java/com/moabam/api/application/room/RoomSearchService.java
  src/main/java/com/moabam/api/application/room/mapper/CertificationsMapper.java
  src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
  src/main/java/com/moabam/api/domain/room/repository/CertificationsSearchRepository.java
  src/main/java/com/moabam/api/domain/room/repository/ParticipantSearchRepository.java
  src/main/java/com/moabam/api/dto/notification/KnockNotificationStatusResponse.java
  src/main/java/com/moabam/api/dto/room/RoomDetailsResponse.java
  src/main/java/com/moabam/api/dto/room/TodayCertificateRankResponse.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/test/java/com/moabam/api/application/notification/NotificationServiceTest.java
  src/test/java/com/moabam/api/domain/room/repository/ParticipantSearchRepositoryTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
Labels: ✨ feature, 🍀 BE

#121 feat: 방 검색 기능 구현
  src/main/java/com/moabam/api/application/room/RoomSearchService.java
  src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
  src/main/java/com/moabam/api/domain/room/repository/RoomRepository.java
  src/main/java/com/moabam/api/dto/room/RoomDetailsResponse.java
  src/main/java/com/moabam/api/dto/room/SearchAllRoomResponse.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/test/java/com/moabam/api/application/room/RoomSearchServiceTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
Labels: ✨ feature, 🍀 BE

#128 feat: 방 수정 전 정보 불러오기 기능 구현
  src/main/java/com/moabam/api/application/room/RoomCertificationService.java
  src/main/java/com/moabam/api/application/room/RoomSearchService.java
  src/main/java/com/moabam/api/application/room/mapper/ParticipantMapper.java
  src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
  src/main/java/com/moabam/api/dto/room/ManageRoomResponse.java
  src/main/java/com/moabam/api/dto/room/ParticipantResponse.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/room/RoomSearchServiceTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
Labels: ✨ feature, 🍀 BE

#129 refactor: 사용하지 않는 API 제거 및 코드 스타일 수정
  src/main/java/com/moabam/api/application/bug/BugMapper.java
  src/main/java/com/moabam/api/application/bug/BugService.java
  src/main/java/com/moabam/api/application/payment/PaymentMapper.java
  src/main/java/com/moabam/api/application/payment/PaymentService.java
  src/main/java/com/moabam/api/application/product/ProductMapper.java
  src/main/java/com/moabam/api/domain/payment/Order.java
  src/main/java/com/moabam/api/domain/payment/Payment.java
  src/main/java/com/moabam/api/dto/bug/TodayBugResponse.java
  src/main/java/com/moabam/api/presentation/BugController.java
  src/main/java/com/moabam/api/presentation/PaymentController.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/api/application/payment/PaymentServiceTest.java
  src/test/java/com/moabam/api/domain/payment/OrderTest.java
  src/test/java/com/moabam/api/domain/payment/PaymentTest.java
  src/test/java/com/moabam/api/presentation/BugControllerTest.java
  src/test/java/com/moabam/api/presentation/PaymentControllerTest.java
  src/test/java/com/moabam/support/fixture/CouponFixture.java
  src/test/java/com/moabam/support/fixture/PaymentFixture.java
Labels: ♻️ refactor, 🍀 BE

#132 feat: Fcm Token 저장 기능 구현
  src/docs/asciidoc/notification.adoc
  src/main/java/com/moabam/api/application/coupon/CouponQueueService.java
  src/main/java/com/moabam/api/application/notification/NotificationService.java
  src/main/java/com/moabam/api/domain/notification/repository/NotificationRepository.java
  src/main/java/com/moabam/api/infrastructure/fcm/FcmRepository.java
  src/main/java/com/moabam/api/infrastructure/fcm/FcmService.java
  src/main/java/com/moabam/api/presentation/CouponController.java
  src/main/java/com/moabam/api/presentation/NotificationController.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/notification/NotificationServiceTest.java
  src/test/java/com/moabam/api/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/moabam/api/infrastructure/fcm/FcmRepositoryTest.java
  src/test/java/com/moabam/api/infrastructure/fcm/FcmServiceTest.java
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
Labels: ♻️ refactor, ✨ feature, 🍀 BE

#134 feat: CouponWallet 엔티티, 레포지토리 구현
  src/main/java/com/moabam/api/domain/coupon/CouponWallet.java
  src/main/java/com/moabam/api/domain/coupon/repository/CouponWalletRepository.java
  src/test/java/com/moabam/api/domain/coupon/CouponWalletTest.java
Labels: ✨ feature, 🍀 BE

#139 refactor: 회원 탈퇴 로직 변경
  src/main/java/com/moabam/api/application/auth/AuthorizationService.java
  src/main/java/com/moabam/api/application/member/MemberService.java
  src/main/java/com/moabam/api/domain/member/Member.java
  src/main/java/com/moabam/api/domain/member/repository/MemberSearchRepository.java
  src/main/java/com/moabam/api/presentation/MemberController.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/auth/AuthorizationServiceTest.java
  src/test/java/com/moabam/api/application/member/MemberServiceTest.java
  src/test/java/com/moabam/api/domain/member/MemberRepositoryTest.java
  src/test/java/com/moabam/api/presentation/MemberControllerTest.java
Labels: ♻️ refactor, 🍀 BE

#141 feat: 벌레 상품 구매 시 CouponWallet 적용
  src/main/java/com/moabam/api/application/bug/BugService.java
  src/main/java/com/moabam/api/application/coupon/CouponService.java
  src/main/java/com/moabam/api/domain/coupon/repository/CouponWalletSearchRepository.java
  src/main/java/com/moabam/api/domain/payment/Payment.java
  src/main/java/com/moabam/api/domain/payment/PaymentStatus.java
  src/main/java/com/moabam/api/dto/product/PurchaseProductRequest.java
  src/main/java/com/moabam/api/presentation/BugController.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/api/application/bug/BugServiceTest.java
  src/test/java/com/moabam/api/domain/coupon/repository/CouponWalletSearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/payment/PaymentTest.java
  src/test/java/com/moabam/api/presentation/BugControllerTest.java
  src/test/java/com/moabam/api/presentation/PaymentControllerTest.java
  src/test/java/com/moabam/support/config/TestQuerydslConfig.java
  src/test/java/com/moabam/support/fixture/CouponFixture.java
Labels: ✨ feature, 🍀 BE

#143 refactor: 방/루틴 전체 리팩토링
  src/main/java/com/moabam/api/application/member/MemberService.java
  src/main/java/com/moabam/api/application/room/CertificationService.java
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/application/room/SearchService.java
  src/main/java/com/moabam/api/application/room/mapper/CertificationsMapper.java
  src/main/java/com/moabam/api/application/room/mapper/ParticipantMapper.java
  src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
  src/main/java/com/moabam/api/domain/item/repository/InventorySearchRepository.java
  src/main/java/com/moabam/api/domain/member/Member.java
  src/main/java/com/moabam/api/domain/room/repository/RoutineRepository.java
  src/main/java/com/moabam/api/domain/room/repository/RoutineSearchRepository.java
  src/main/java/com/moabam/api/dto/room/CertificationImagesResponse.java
  src/main/java/com/moabam/api/dto/room/GetAllRoomResponse.java
  src/main/java/com/moabam/api/dto/room/GetAllRoomsResponse.java
  src/main/java/com/moabam/api/dto/room/TodayCertificateRankResponse.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/main/java/com/moabam/global/common/util/BaseImageUrl.java
  src/main/java/com/moabam/global/common/util/ClockHolder.java
  src/main/java/com/moabam/global/common/util/GlobalConstant.java
  src/main/java/com/moabam/global/common/util/SystemClockHolder.java
  src/test/java/com/moabam/api/application/member/MemberServiceTest.java
  src/test/java/com/moabam/api/application/room/CertificationServiceTest.java
  src/test/java/com/moabam/api/application/room/RoomServiceTest.java
  src/test/java/com/moabam/api/application/room/SearchServiceTest.java
  src/test/java/com/moabam/api/domain/entity/MemberTest.java
  src/test/java/com/moabam/api/domain/item/repository/InventorySearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/member/MemberRepositoryTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
Labels: ♻️ refactor, 🍀 BE

#148 refactor: 쿠폰, 알림 테스트 접근 제어자, 메서드명, 클래스명 변경
  src/main/java/com/moabam/api/application/coupon/CouponManageService.java
  src/main/java/com/moabam/api/application/coupon/CouponService.java
  src/main/java/com/moabam/api/application/notification/NotificationService.java
  src/main/java/com/moabam/api/domain/coupon/repository/CouponManageRepository.java
  src/main/java/com/moabam/api/domain/notification/repository/NotificationRepository.java
  src/main/java/com/moabam/api/infrastructure/fcm/FcmRepository.java
  src/main/java/com/moabam/api/infrastructure/redis/ValueRedisRepository.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/moabam/api/application/coupon/CouponManageServiceTest.java
  src/test/java/com/moabam/api/application/coupon/CouponServiceTest.java
  src/test/java/com/moabam/api/application/notification/NotificationServiceTest.java
  src/test/java/com/moabam/api/domain/coupon/CouponTest.java
  src/test/java/com/moabam/api/domain/coupon/CouponTypeTest.java
  src/test/java/com/moabam/api/domain/coupon/CouponWalletTest.java
  src/test/java/com/moabam/api/domain/coupon/repository/CouponManageRepositoryTest.java
  src/test/java/com/moabam/api/domain/coupon/repository/CouponSearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/coupon/repository/CouponWalletSearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/moabam/api/dto/coupon/CreateCouponRequestTest.java
  src/test/java/com/moabam/api/infrastructure/fcm/FcmRepositoryTest.java
  src/test/java/com/moabam/api/infrastructure/fcm/FcmServiceTest.java
  src/test/java/com/moabam/api/infrastructure/redis/ValueRedisRepositoryTest.java
  src/test/java/com/moabam/api/infrastructure/redis/ZSetRedisRepositoryTest.java
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
Labels: ♻️ refactor, 🍀 BE

#149 feat: 쿠폰 보관함 조회 기능 구현
  src/docs/asciidoc/coupon.adoc
  src/main/java/com/moabam/api/application/coupon/CouponMapper.java
  src/main/java/com/moabam/api/application/coupon/CouponService.java
  src/main/java/com/moabam/api/application/notification/NotificationService.java
  src/main/java/com/moabam/api/domain/coupon/repository/CouponWalletSearchRepository.java
  src/main/java/com/moabam/api/dto/coupon/MyCouponResponse.java
  src/main/java/com/moabam/api/presentation/CouponController.java
  src/main/resources/static/docs/coupon.html
  src/test/java/com/moabam/api/application/coupon/CouponServiceTest.java
  src/test/java/com/moabam/api/domain/coupon/repository/CouponWalletSearchRepositoryTest.java
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
  src/test/java/com/moabam/support/fixture/CouponFixture.java
  src/test/java/com/moabam/support/fixture/CouponWalletFixture.java
  src/test/java/com/moabam/support/snippet/CouponSnippet.java
  src/test/java/com/moabam/support/snippet/CouponWalletSnippet.java
  src/test/java/com/moabam/support/snippet/ErrorSnippet.java
Labels: ✨ feature, 🍀 BE

#155 feat: 벌레 내역 조회 기능 구현
  src/main/java/com/moabam/api/application/bug/BugMapper.java
  src/main/java/com/moabam/api/application/bug/BugService.java
  src/main/java/com/moabam/api/application/coupon/CouponService.java
  src/main/java/com/moabam/api/application/payment/PaymentMapper.java
  src/main/java/com/moabam/api/domain/bug/BugHistory.java
  src/main/java/com/moabam/api/domain/bug/repository/BugHistorySearchRepository.java
  src/main/java/com/moabam/api/domain/coupon/repository/CouponWalletRepository.java
  src/main/java/com/moabam/api/dto/bug/BugHistoryItemResponse.java
  src/main/java/com/moabam/api/dto/bug/BugHistoryResponse.java
  src/main/java/com/moabam/api/dto/bug/BugHistoryWithPayment.java
  src/main/java/com/moabam/api/dto/payment/PaymentResponse.java
  src/main/java/com/moabam/api/presentation/BugController.java
  src/main/java/com/moabam/global/common/util/DateUtils.java
  src/test/java/com/moabam/api/domain/bug/BugTest.java
  src/test/java/com/moabam/api/presentation/BugControllerTest.java
  src/test/java/com/moabam/support/fixture/BugFixture.java
Labels: ✨ feature, 🍀 BE

#157 feat: 방 인증, 입장 동시성 처리
  .github/workflows/ci.yml
  src/main/java/com/moabam/api/application/room/CertificationService.java
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/application/room/mapper/CertificationsMapper.java
  src/main/java/com/moabam/api/domain/image/ImageName.java
  src/main/java/com/moabam/api/domain/image/ImageResizer.java
  src/main/java/com/moabam/api/domain/image/ImageType.java
  src/main/java/com/moabam/api/domain/room/Room.java
  src/main/java/com/moabam/api/domain/room/repository/CertificationsSearchRepository.java
  src/main/java/com/moabam/api/domain/room/repository/RoomRepository.java
  src/main/java/com/moabam/api/dto/room/CertifiedMemberInfo.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/main/java/com/moabam/global/common/util/GlobalConstant.java
  src/test/java/com/moabam/api/application/image/ImageServiceTest.java
  src/test/java/com/moabam/api/application/room/CertificationServiceConcurrencyTest.java
  src/test/java/com/moabam/api/application/room/CertificationServiceTest.java
  src/test/java/com/moabam/api/application/room/RoomServiceConcurrencyTest.java
  src/test/java/com/moabam/api/domain/coupon/repository/CouponSearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/item/repository/InventorySearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/member/MemberRepositoryTest.java
  src/test/java/com/moabam/api/domain/room/repository/ParticipantSearchRepositoryTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
  src/test/java/com/moabam/support/annotation/QuerydslRepositoryTest.java
  src/test/resources/application.yml
Labels: ✨ feature, 🍀 BE

#165 feat: 벌레 보상/충전/사용 시 내역 저장 로직 추가
  src/main/java/com/moabam/api/application/bug/BugMapper.java
  src/main/java/com/moabam/api/application/bug/BugService.java
  src/main/java/com/moabam/api/application/coupon/CouponService.java
  src/main/java/com/moabam/api/application/item/ItemService.java
  src/main/java/com/moabam/api/application/room/CertificationService.java
  src/main/java/com/moabam/api/domain/bug/Bug.java
  src/main/java/com/moabam/api/presentation/ItemController.java
  src/test/java/com/moabam/api/application/bug/BugServiceTest.java
  src/test/java/com/moabam/api/application/coupon/CouponServiceTest.java
  src/test/java/com/moabam/api/application/item/ItemServiceTest.java
  src/test/java/com/moabam/api/application/room/CertificationServiceTest.java
  src/test/java/com/moabam/api/presentation/ItemControllerTest.java
Labels: ✨ feature, 🍀 BE

#167 feat: 아이템 이미지 버전 추가 및 방 배경 업데이트
  src/main/java/com/moabam/api/application/item/ItemMapper.java
  src/main/java/com/moabam/api/application/member/MemberService.java
  src/main/java/com/moabam/api/application/room/SearchService.java
  src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
  src/main/java/com/moabam/api/domain/item/Item.java
  src/main/java/com/moabam/api/domain/item/ItemImage.java
  src/main/java/com/moabam/api/domain/member/Member.java
  src/main/java/com/moabam/api/domain/room/Room.java
  src/test/java/com/moabam/api/application/member/MemberServiceTest.java
  src/test/java/com/moabam/api/domain/room/RoomTest.java
  src/test/java/com/moabam/api/presentation/MemberControllerTest.java
  src/test/java/com/moabam/support/fixture/ItemFixture.java
Labels: ✨ feature, 🍀 BE

#177 fix: 방장 자신에 대한 추방 버그
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/application/room/SearchService.java
  src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
  src/main/java/com/moabam/api/domain/room/repository/ParticipantSearchRepository.java
  src/main/java/com/moabam/api/dto/room/ManageRoomResponse.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
Labels: 🍀 BE, 🐛 fix

#178 Fix/#175 fix member delete error
  src/main/java/com/moabam/api/application/member/MemberService.java
  src/main/java/com/moabam/api/application/report/ReportService.java
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/domain/member/BadgeType.java
  src/main/java/com/moabam/api/domain/member/Member.java
  src/main/java/com/moabam/api/domain/room/repository/ParticipantRepository.java
  src/main/java/com/moabam/api/domain/room/repository/ParticipantSearchRepository.java
  src/main/java/com/moabam/api/dto/member/BadgeResponse.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
  src/test/java/com/moabam/api/application/member/MemberServiceTest.java
  src/test/java/com/moabam/api/application/report/ReportServiceTest.java
  src/test/java/com/moabam/api/application/room/RoomServiceTest.java
  src/test/java/com/moabam/api/presentation/MemberControllerTest.java
  src/test/java/com/moabam/api/presentation/ReportControllerTest.java
Labels: 🍀 BE, 🐛 fix

#183 style: FCM Token Log 생성
  src/main/java/com/moabam/api/infrastructure/fcm/FcmService.java
Labels: ♻️ refactor, 🍀 BE

#184 fix: 방장 방 나가기 안되는 버그 수정
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
Labels: 🍀 BE, 🐛 fix

#185 fix: fcm 토큰 삭제 기능 추가
  src/main/java/com/moabam/api/application/auth/AuthorizationService.java
  src/main/java/com/moabam/api/application/member/MemberService.java
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/infrastructure/fcm/FcmService.java
  src/main/java/com/moabam/global/auth/filter/AuthorizationFilter.java
  src/test/java/com/moabam/api/application/auth/AuthorizationServiceTest.java
  src/test/java/com/moabam/api/application/member/MemberServiceTest.java
Labels: 🍀 BE, 🐛 fix

#193 fix: 루틴 인증 사진 업로드 안되는 버그 해결
  src/main/java/com/moabam/api/application/image/ImageService.java
  src/main/java/com/moabam/api/domain/image/ImageResizer.java
  src/main/java/com/moabam/api/domain/image/NewImage.java
  src/main/java/com/moabam/api/dto/room/CertifyRoomRequest.java
  src/main/java/com/moabam/api/dto/room/CertifyRoomsRequest.java
  src/main/java/com/moabam/api/presentation/RoomController.java
  src/test/java/com/moabam/api/application/image/ImageServiceTest.java
Labels: 🍀 BE, 🐛 fix

#194 fix: 토스 결제 승인 성공/실패 시 결과 반영 안되는 이슈 해결
  src/main/java/com/moabam/api/application/payment/PaymentMapper.java
  src/main/java/com/moabam/api/application/payment/PaymentService.java
  src/main/java/com/moabam/api/dto/payment/RequestConfirmPaymentResponse.java
  src/main/java/com/moabam/api/infrastructure/payment/TossPaymentService.java
  src/main/java/com/moabam/api/presentation/PaymentController.java
  src/test/java/com/moabam/api/application/payment/PaymentServiceTest.java
  src/test/java/com/moabam/api/presentation/PaymentControllerTest.java
Labels: 🍀 BE, 🐛 fix

#189 feat: ranking system 구현
  src/main/java/com/moabam/api/application/member/MemberMapper.java
  src/main/java/com/moabam/api/application/member/MemberService.java
  src/main/java/com/moabam/api/application/ranking/RankingMapper.java
  src/main/java/com/moabam/api/application/ranking/RankingService.java
  src/main/java/com/moabam/api/domain/member/repository/MemberSearchRepository.java
  src/main/java/com/moabam/api/dto/ranking/RankingInfo.java
  src/main/java/com/moabam/api/dto/ranking/TopRankingInfo.java
  src/main/java/com/moabam/api/dto/ranking/TopRankingResponse.java
  src/main/java/com/moabam/api/dto/ranking/UpdateRanking.java
  src/main/java/com/moabam/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/moabam/api/presentation/RankingController.java
  src/main/java/com/moabam/global/config/EmbeddedRedisConfig.java
  src/main/java/com/moabam/global/config/RedisConfig.java
  src/test/java/com/moabam/api/application/member/MemberServiceTest.java
  src/test/java/com/moabam/api/application/ranking/RankingServiceTest.java
  src/test/java/com/moabam/api/application/room/CertificationServiceConcurrencyTest.java
  src/test/java/com/moabam/api/application/room/CertificationServiceTest.java
  src/test/java/com/moabam/api/application/room/RoomServiceConcurrencyTest.java
  src/test/java/com/moabam/api/application/room/RoomServiceTest.java
  src/test/java/com/moabam/api/domain/item/repository/InventorySearchRepositoryTest.java
  src/test/java/com/moabam/api/domain/member/MemberRepositoryTest.java
  src/test/java/com/moabam/api/presentation/MemberControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
  src/test/java/com/moabam/api/presentation/RankingControllerTest.java
  src/test/java/com/moabam/api/presentation/ReportControllerTest.java
  src/test/java/com/moabam/api/presentation/RoomControllerTest.java
  src/test/java/com/moabam/support/fixture/MemberFixture.java
  src/test/java/com/moabam/support/fixture/RankingInfoFixture.java
Labels: ✨ feature, 🍀 BE

#195 fix: record를 class로 바꿔서 바인딩 해결
  src/main/java/com/moabam/api/application/image/ImageService.java
  src/main/java/com/moabam/api/dto/room/CertifyRoomRequest.java
  src/main/java/com/moabam/api/dto/room/CertifyRoomsRequest.java
  src/main/java/com/moabam/global/error/model/ErrorMessage.java
Labels: 🍀 BE, 🐛 fix

#197 fix: approvedAt 변환 오류 수정
  src/main/java/com/moabam/api/dto/payment/ConfirmTossPaymentResponse.java
  src/test/java/com/moabam/support/fixture/PaymentFixture.java
Labels: 🍀 BE, 🐛 fix

#201 refactor: 방 상세 정보에 방 생성 날짜시간 추가
  src/main/java/com/moabam/api/application/room/mapper/RoomMapper.java
  src/main/java/com/moabam/api/dto/room/RoomDetailsResponse.java
Labels: ♻️ refactor, 🍀 BE

#204 fix: ObjectMapper 삭제 실패 수정
  src/main/java/com/moabam/global/config/RedisConfig.java
Labels: 🍀 BE, 🐛 fix

#208 refactor: infra 디렉토리 생성 및 리팩터링
  infra/nginx/templates/ssl-server.template
  infra/scripts/deploy-dev.sh
  infra/scripts/init-letsencrypt.sh
  infra/scripts/init-nginx-converter.sh
Labels: ♻️ refactor, 🍀 BE
