Repository team-moabam/moabam-BE, pull requests merged in 2024-01, with the labels that each got.

#255 feat: 쿠폰 캐싱 기능 구현
  README.md
  build.gradle
  readme-image/img.png
  readme-image/img_1.png
  readme-image/서비스-아키텍처.png
  readme-image/컨벤션.png
  readme-image/콘피그.png
  readme-image/테스트.png
  readme-image/파이프라인.png
  readme-image/협업.png
  src/main/java/com/moabam/api/application/coupon/CouponCacheService.java
  src/main/java/com/moabam/api/application/coupon/CouponManageService.java
  src/main/java/com/moabam/api/application/member/MemberService.java
  src/main/java/com/moabam/api/application/notification/NotificationService.java
  src/main/java/com/moabam/api/application/room/CertificationService.java
  src/main/java/com/moabam/api/application/room/RoomService.java
  src/main/java/com/moabam/api/application/room/SearchService.java
  src/main/java/com/moabam/api/domain/coupon/repository/CouponRepository.java
  src/main/java/com/moabam/global/common/util/ClockHolder.java
  src/main/java/com/moabam/global/common/util/SystemClockHolder.java
  src/main/java/com/moabam/global/config/CacheConfig.java
  src/test/java/com/moabam/api/application/coupon/CouponManageServiceTest.java
  src/test/java/com/moabam/api/application/member/MemberServiceTest.java
  src/test/java/com/moabam/api/application/notification/NotificationServiceTest.java
  src/test/java/com/moabam/api/application/room/CertificationServiceTest.java
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/support/common/TestClockHolder.java
Labels: 🍀 BE

#258 refactor: Match Against 변경
  infra/mysql/initdb.d/init.sql
  src/main/java/com/moabam/api/domain/room/Room.java
  src/main/java/com/moabam/api/domain/room/repository/RoomSearchRepository.java
  src/main/java/com/moabam/global/config/SqlFunctionContributor.java
Labels: ♻️ refactor, 🍀 BE

#259 feat: restdoc openapi 연동
  .gitignore
  README.md
  build.gradle
  readme-image/api.png
  readme-image/table.png
  src/main/java/com/moabam/global/auth/filter/CorsFilter.java
  src/main/java/com/moabam/global/config/WebConfig.java
  src/main/resources/static/docs/coupon.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/notification.html
  src/main/resources/static/docs/openapi3.json
  src/test/java/com/moabam/api/presentation/CouponControllerTest.java
  src/test/java/com/moabam/api/presentation/NotificationControllerTest.java
Labels: 🍀 BE

#261 refactor: Readme 수정
  README.md
Labels: ⚙️ setting, 🍀 BE
